# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_alg_gfunc.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_AlgoGFuncStmt(object):
    def setupUi(self, AlgoGFuncStmt):
        AlgoGFuncStmt.setObjectName("AlgoGFuncStmt")
        AlgoGFuncStmt.setWindowModality(QtCore.Qt.WindowModal)
        AlgoGFuncStmt.resize(477, 251)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/action/media/settings.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        AlgoGFuncStmt.setWindowIcon(icon)
        AlgoGFuncStmt.setModal(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(AlgoGFuncStmt)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(AlgoGFuncStmt)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_6 = QtWidgets.QLabel(AlgoGFuncStmt)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 2, 0, 1, 1)
        self.txtStart = QtWidgets.QLineEdit(AlgoGFuncStmt)
        self.txtStart.setObjectName("txtStart")
        self.gridLayout.addWidget(self.txtStart, 2, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(AlgoGFuncStmt)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 4, 0, 1, 1)
        self.txtColor = QtWidgets.QLineEdit(AlgoGFuncStmt)
        self.txtColor.setObjectName("txtColor")
        self.gridLayout.addWidget(self.txtColor, 5, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(AlgoGFuncStmt)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 1, 0, 1, 1)
        self.txtStep = QtWidgets.QLineEdit(AlgoGFuncStmt)
        self.txtStep.setObjectName("txtStep")
        self.gridLayout.addWidget(self.txtStep, 4, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(AlgoGFuncStmt)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.txtVariable = QtWidgets.QLineEdit(AlgoGFuncStmt)
        self.txtVariable.setObjectName("txtVariable")
        self.gridLayout.addWidget(self.txtVariable, 0, 1, 1, 1)
        self.btnCodeFunction = QtWidgets.QPushButton(AlgoGFuncStmt)
        self.btnCodeFunction.setEnabled(True)
        self.btnCodeFunction.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/action/media/edit_line.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnCodeFunction.setIcon(icon1)
        self.btnCodeFunction.setObjectName("btnCodeFunction")
        self.gridLayout.addWidget(self.btnCodeFunction, 1, 2, 1, 1)
        self.btnCodeColor = QtWidgets.QPushButton(AlgoGFuncStmt)
        self.btnCodeColor.setEnabled(True)
        self.btnCodeColor.setText("")
        self.btnCodeColor.setIcon(icon1)
        self.btnCodeColor.setObjectName("btnCodeColor")
        self.gridLayout.addWidget(self.btnCodeColor, 5, 2, 1, 1)
        self.btnCodeStep = QtWidgets.QPushButton(AlgoGFuncStmt)
        self.btnCodeStep.setEnabled(True)
        self.btnCodeStep.setText("")
        self.btnCodeStep.setIcon(icon1)
        self.btnCodeStep.setObjectName("btnCodeStep")
        self.gridLayout.addWidget(self.btnCodeStep, 4, 2, 1, 1)
        self.txtFunction = QtWidgets.QLineEdit(AlgoGFuncStmt)
        self.txtFunction.setObjectName("txtFunction")
        self.gridLayout.addWidget(self.txtFunction, 1, 1, 1, 1)
        self.btnCodeStart = QtWidgets.QPushButton(AlgoGFuncStmt)
        self.btnCodeStart.setEnabled(True)
        self.btnCodeStart.setText("")
        self.btnCodeStart.setIcon(icon1)
        self.btnCodeStart.setObjectName("btnCodeStart")
        self.gridLayout.addWidget(self.btnCodeStart, 2, 2, 1, 1)
        self.label_8 = QtWidgets.QLabel(AlgoGFuncStmt)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 5, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(AlgoGFuncStmt)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 3, 0, 1, 1)
        self.txtEnd = QtWidgets.QLineEdit(AlgoGFuncStmt)
        self.txtEnd.setObjectName("txtEnd")
        self.gridLayout.addWidget(self.txtEnd, 3, 1, 1, 1)
        self.btnCodeEnd = QtWidgets.QPushButton(AlgoGFuncStmt)
        self.btnCodeEnd.setEnabled(True)
        self.btnCodeEnd.setText("")
        self.btnCodeEnd.setIcon(icon1)
        self.btnCodeEnd.setObjectName("btnCodeEnd")
        self.gridLayout.addWidget(self.btnCodeEnd, 3, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(AlgoGFuncStmt)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)
        self.label_6.setBuddy(self.txtStart)
        self.label_7.setBuddy(self.txtStep)
        self.label_5.setBuddy(self.txtFunction)
        self.label_2.setBuddy(self.txtVariable)
        self.label_8.setBuddy(self.txtColor)
        self.label_9.setBuddy(self.txtStart)

        self.retranslateUi(AlgoGFuncStmt)
        self.buttonBox.accepted.connect(AlgoGFuncStmt.accept)
        self.buttonBox.rejected.connect(AlgoGFuncStmt.reject)
        QtCore.QMetaObject.connectSlotsByName(AlgoGFuncStmt)
        AlgoGFuncStmt.setTabOrder(self.txtVariable, self.txtFunction)
        AlgoGFuncStmt.setTabOrder(self.txtFunction, self.txtStart)
        AlgoGFuncStmt.setTabOrder(self.txtStart, self.txtStep)
        AlgoGFuncStmt.setTabOrder(self.txtStep, self.txtColor)
        AlgoGFuncStmt.setTabOrder(self.txtColor, self.btnCodeFunction)
        AlgoGFuncStmt.setTabOrder(self.btnCodeFunction, self.btnCodeStart)
        AlgoGFuncStmt.setTabOrder(self.btnCodeStart, self.btnCodeStep)
        AlgoGFuncStmt.setTabOrder(self.btnCodeStep, self.btnCodeColor)

    def retranslateUi(self, AlgoGFuncStmt):
        _translate = QtCore.QCoreApplication.translate
        AlgoGFuncStmt.setWindowTitle(_translate("AlgoGFuncStmt", "Plot function"))
        self.label.setText(_translate("AlgoGFuncStmt", "<html><head/><body><p>Draws the curve of the function on the specified interval.</p><p>The color must be a string containing the color name or RGB hex string.</p></body></html>"))
        self.label_6.setText(_translate("AlgoGFuncStmt", "Start:"))
        self.label_7.setText(_translate("AlgoGFuncStmt", "Step:"))
        self.label_5.setText(_translate("AlgoGFuncStmt", "Function:"))
        self.label_2.setText(_translate("AlgoGFuncStmt", "Variable:"))
        self.label_8.setText(_translate("AlgoGFuncStmt", "Color:"))
        self.label_9.setText(_translate("AlgoGFuncStmt", "End:"))

import turing_rc
