# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_alg_gwindow.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_AlgoGWindowStmt(object):
    def setupUi(self, AlgoGWindowStmt):
        AlgoGWindowStmt.setObjectName("AlgoGWindowStmt")
        AlgoGWindowStmt.setWindowModality(QtCore.Qt.WindowModal)
        AlgoGWindowStmt.resize(477, 251)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/action/media/settings.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        AlgoGWindowStmt.setWindowIcon(icon)
        AlgoGWindowStmt.setModal(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(AlgoGWindowStmt)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(AlgoGWindowStmt)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.txtYmin = QtWidgets.QLineEdit(AlgoGWindowStmt)
        self.txtYmin.setObjectName("txtYmin")
        self.gridLayout.addWidget(self.txtYmin, 2, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(AlgoGWindowStmt)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 3, 0, 1, 1)
        self.txtXgrad = QtWidgets.QLineEdit(AlgoGWindowStmt)
        self.txtXgrad.setObjectName("txtXgrad")
        self.gridLayout.addWidget(self.txtXgrad, 4, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(AlgoGWindowStmt)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 2, 0, 1, 1)
        self.txtYmax = QtWidgets.QLineEdit(AlgoGWindowStmt)
        self.txtYmax.setObjectName("txtYmax")
        self.gridLayout.addWidget(self.txtYmax, 3, 1, 1, 1)
        self.txtXmin = QtWidgets.QLineEdit(AlgoGWindowStmt)
        self.txtXmin.setObjectName("txtXmin")
        self.gridLayout.addWidget(self.txtXmin, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(AlgoGWindowStmt)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(AlgoGWindowStmt)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 1, 0, 1, 1)
        self.btnCodeXmin = QtWidgets.QPushButton(AlgoGWindowStmt)
        self.btnCodeXmin.setEnabled(True)
        self.btnCodeXmin.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/action/media/edit_line.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnCodeXmin.setIcon(icon1)
        self.btnCodeXmin.setObjectName("btnCodeXmin")
        self.gridLayout.addWidget(self.btnCodeXmin, 0, 2, 1, 1)
        self.txtXmax = QtWidgets.QLineEdit(AlgoGWindowStmt)
        self.txtXmax.setObjectName("txtXmax")
        self.gridLayout.addWidget(self.txtXmax, 1, 1, 1, 1)
        self.btnCodeXmax = QtWidgets.QPushButton(AlgoGWindowStmt)
        self.btnCodeXmax.setEnabled(True)
        self.btnCodeXmax.setText("")
        self.btnCodeXmax.setIcon(icon1)
        self.btnCodeXmax.setObjectName("btnCodeXmax")
        self.gridLayout.addWidget(self.btnCodeXmax, 1, 2, 1, 1)
        self.txtYgrad = QtWidgets.QLineEdit(AlgoGWindowStmt)
        self.txtYgrad.setObjectName("txtYgrad")
        self.gridLayout.addWidget(self.txtYgrad, 5, 1, 1, 1)
        self.btnCodeYmin = QtWidgets.QPushButton(AlgoGWindowStmt)
        self.btnCodeYmin.setEnabled(True)
        self.btnCodeYmin.setText("")
        self.btnCodeYmin.setIcon(icon1)
        self.btnCodeYmin.setObjectName("btnCodeYmin")
        self.gridLayout.addWidget(self.btnCodeYmin, 2, 2, 1, 1)
        self.btnCodeYmax = QtWidgets.QPushButton(AlgoGWindowStmt)
        self.btnCodeYmax.setEnabled(True)
        self.btnCodeYmax.setText("")
        self.btnCodeYmax.setIcon(icon1)
        self.btnCodeYmax.setObjectName("btnCodeYmax")
        self.gridLayout.addWidget(self.btnCodeYmax, 3, 2, 1, 1)
        self.btnCodeXgrad = QtWidgets.QPushButton(AlgoGWindowStmt)
        self.btnCodeXgrad.setEnabled(True)
        self.btnCodeXgrad.setText("")
        self.btnCodeXgrad.setIcon(icon1)
        self.btnCodeXgrad.setObjectName("btnCodeXgrad")
        self.gridLayout.addWidget(self.btnCodeXgrad, 4, 2, 1, 1)
        self.btnCodeYgrad = QtWidgets.QPushButton(AlgoGWindowStmt)
        self.btnCodeYgrad.setEnabled(True)
        self.btnCodeYgrad.setText("")
        self.btnCodeYgrad.setIcon(icon1)
        self.btnCodeYgrad.setObjectName("btnCodeYgrad")
        self.gridLayout.addWidget(self.btnCodeYgrad, 5, 2, 1, 1)
        self.label_8 = QtWidgets.QLabel(AlgoGWindowStmt)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 4, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(AlgoGWindowStmt)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 5, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(AlgoGWindowStmt)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)
        self.label_7.setBuddy(self.txtYmax)
        self.label_6.setBuddy(self.txtYmin)
        self.label_2.setBuddy(self.txtXmin)
        self.label_5.setBuddy(self.txtXmax)
        self.label_8.setBuddy(self.txtXgrad)
        self.label_9.setBuddy(self.txtYgrad)

        self.retranslateUi(AlgoGWindowStmt)
        self.buttonBox.accepted.connect(AlgoGWindowStmt.accept)
        self.buttonBox.rejected.connect(AlgoGWindowStmt.reject)
        QtCore.QMetaObject.connectSlotsByName(AlgoGWindowStmt)
        AlgoGWindowStmt.setTabOrder(self.txtXmin, self.txtXmax)
        AlgoGWindowStmt.setTabOrder(self.txtXmax, self.txtYmin)
        AlgoGWindowStmt.setTabOrder(self.txtYmin, self.txtYmax)
        AlgoGWindowStmt.setTabOrder(self.txtYmax, self.txtXgrad)
        AlgoGWindowStmt.setTabOrder(self.txtXgrad, self.txtYgrad)
        AlgoGWindowStmt.setTabOrder(self.txtYgrad, self.btnCodeXmin)
        AlgoGWindowStmt.setTabOrder(self.btnCodeXmin, self.btnCodeXmax)
        AlgoGWindowStmt.setTabOrder(self.btnCodeXmax, self.btnCodeYmin)
        AlgoGWindowStmt.setTabOrder(self.btnCodeYmin, self.btnCodeYmax)
        AlgoGWindowStmt.setTabOrder(self.btnCodeYmax, self.btnCodeXgrad)
        AlgoGWindowStmt.setTabOrder(self.btnCodeXgrad, self.btnCodeYgrad)

    def retranslateUi(self, AlgoGWindowStmt):
        _translate = QtCore.QCoreApplication.translate
        AlgoGWindowStmt.setWindowTitle(_translate("AlgoGWindowStmt", "Canvas size"))
        self.label.setText(_translate("AlgoGWindowStmt", "<html><head/><body><p>Changes the size of the plot window canvas.</p></body></html>"))
        self.label_7.setText(_translate("AlgoGWindowStmt", "Max Y:"))
        self.label_6.setText(_translate("AlgoGWindowStmt", "Min Y:"))
        self.label_2.setText(_translate("AlgoGWindowStmt", "Min X:"))
        self.label_5.setText(_translate("AlgoGWindowStmt", "Max X:"))
        self.label_8.setText(_translate("AlgoGWindowStmt", "Grad X:"))
        self.label_9.setText(_translate("AlgoGWindowStmt", "Grad Y:"))

import turing_rc
