# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_alg_gline.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_AlgoGLineStmt(object):
    def setupUi(self, AlgoGLineStmt):
        AlgoGLineStmt.setObjectName("AlgoGLineStmt")
        AlgoGLineStmt.setWindowModality(QtCore.Qt.WindowModal)
        AlgoGLineStmt.resize(477, 251)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/action/media/settings.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        AlgoGLineStmt.setWindowIcon(icon)
        AlgoGLineStmt.setModal(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(AlgoGLineStmt)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(AlgoGLineStmt)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.txtColor = QtWidgets.QLineEdit(AlgoGLineStmt)
        self.txtColor.setObjectName("txtColor")
        self.gridLayout.addWidget(self.txtColor, 4, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(AlgoGLineStmt)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 3, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(AlgoGLineStmt)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 2, 0, 1, 1)
        self.txtEndX = QtWidgets.QLineEdit(AlgoGLineStmt)
        self.txtEndX.setObjectName("txtEndX")
        self.gridLayout.addWidget(self.txtEndX, 2, 1, 1, 1)
        self.txtEndY = QtWidgets.QLineEdit(AlgoGLineStmt)
        self.txtEndY.setObjectName("txtEndY")
        self.gridLayout.addWidget(self.txtEndY, 3, 1, 1, 1)
        self.txtStartX = QtWidgets.QLineEdit(AlgoGLineStmt)
        self.txtStartX.setObjectName("txtStartX")
        self.gridLayout.addWidget(self.txtStartX, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(AlgoGLineStmt)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(AlgoGLineStmt)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 1, 0, 1, 1)
        self.btnCodeStartX = QtWidgets.QPushButton(AlgoGLineStmt)
        self.btnCodeStartX.setEnabled(True)
        self.btnCodeStartX.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/action/media/edit_line.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnCodeStartX.setIcon(icon1)
        self.btnCodeStartX.setObjectName("btnCodeStartX")
        self.gridLayout.addWidget(self.btnCodeStartX, 0, 2, 1, 1)
        self.btnCodeColor = QtWidgets.QPushButton(AlgoGLineStmt)
        self.btnCodeColor.setEnabled(True)
        self.btnCodeColor.setText("")
        self.btnCodeColor.setIcon(icon1)
        self.btnCodeColor.setObjectName("btnCodeColor")
        self.gridLayout.addWidget(self.btnCodeColor, 4, 2, 1, 1)
        self.btnCodeStartY = QtWidgets.QPushButton(AlgoGLineStmt)
        self.btnCodeStartY.setEnabled(True)
        self.btnCodeStartY.setText("")
        self.btnCodeStartY.setIcon(icon1)
        self.btnCodeStartY.setObjectName("btnCodeStartY")
        self.gridLayout.addWidget(self.btnCodeStartY, 1, 2, 1, 1)
        self.txtStartY = QtWidgets.QLineEdit(AlgoGLineStmt)
        self.txtStartY.setObjectName("txtStartY")
        self.gridLayout.addWidget(self.txtStartY, 1, 1, 1, 1)
        self.btnCodeEndX = QtWidgets.QPushButton(AlgoGLineStmt)
        self.btnCodeEndX.setEnabled(True)
        self.btnCodeEndX.setText("")
        self.btnCodeEndX.setIcon(icon1)
        self.btnCodeEndX.setObjectName("btnCodeEndX")
        self.gridLayout.addWidget(self.btnCodeEndX, 2, 2, 1, 1)
        self.btnCodeEndY = QtWidgets.QPushButton(AlgoGLineStmt)
        self.btnCodeEndY.setEnabled(True)
        self.btnCodeEndY.setText("")
        self.btnCodeEndY.setIcon(icon1)
        self.btnCodeEndY.setObjectName("btnCodeEndY")
        self.gridLayout.addWidget(self.btnCodeEndY, 3, 2, 1, 1)
        self.label_8 = QtWidgets.QLabel(AlgoGLineStmt)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 4, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(AlgoGLineStmt)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)
        self.label_7.setBuddy(self.txtEndY)
        self.label_6.setBuddy(self.txtEndX)
        self.label_2.setBuddy(self.txtStartX)
        self.label_5.setBuddy(self.txtStartY)
        self.label_8.setBuddy(self.txtColor)

        self.retranslateUi(AlgoGLineStmt)
        self.buttonBox.accepted.connect(AlgoGLineStmt.accept)
        self.buttonBox.rejected.connect(AlgoGLineStmt.reject)
        QtCore.QMetaObject.connectSlotsByName(AlgoGLineStmt)
        AlgoGLineStmt.setTabOrder(self.txtStartX, self.txtStartY)
        AlgoGLineStmt.setTabOrder(self.txtStartY, self.txtEndX)
        AlgoGLineStmt.setTabOrder(self.txtEndX, self.txtEndY)
        AlgoGLineStmt.setTabOrder(self.txtEndY, self.txtColor)
        AlgoGLineStmt.setTabOrder(self.txtColor, self.btnCodeStartX)
        AlgoGLineStmt.setTabOrder(self.btnCodeStartX, self.btnCodeStartY)
        AlgoGLineStmt.setTabOrder(self.btnCodeStartY, self.btnCodeEndX)
        AlgoGLineStmt.setTabOrder(self.btnCodeEndX, self.btnCodeEndY)
        AlgoGLineStmt.setTabOrder(self.btnCodeEndY, self.btnCodeColor)

    def retranslateUi(self, AlgoGLineStmt):
        _translate = QtCore.QCoreApplication.translate
        AlgoGLineStmt.setWindowTitle(_translate("AlgoGLineStmt", "Plot line"))
        self.label.setText(_translate("AlgoGLineStmt", "<html><head/><body><p>Draws a line with the specified coordinates.</p><p>The color must be a string containing the color name or RGB hex string.</p></body></html>"))
        self.label_7.setText(_translate("AlgoGLineStmt", "End Y:"))
        self.label_6.setText(_translate("AlgoGLineStmt", "End X:"))
        self.label_2.setText(_translate("AlgoGLineStmt", "Start X:"))
        self.label_5.setText(_translate("AlgoGLineStmt", "Start Y:"))
        self.label_8.setText(_translate("AlgoGLineStmt", "Color:"))

import turing_rc
