# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(900, 713)
        MainWindow.setMinimumSize(QtCore.QSize(800, 0))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/media/icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setUnifiedTitleAndToolBarOnMac(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setAcceptDrops(True)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_home = QtWidgets.QWidget()
        self.tab_home.setObjectName("tab_home")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab_home)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/action/media/home.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab_home, icon1, "")
        self.tab_pseudocode = QtWidgets.QWidget()
        self.tab_pseudocode.setObjectName("tab_pseudocode")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.tab_pseudocode)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.treeWidget = QtWidgets.QTreeWidget(self.tab_pseudocode)
        self.treeWidget.setAlternatingRowColors(True)
        self.treeWidget.setAnimated(True)
        self.treeWidget.setHeaderHidden(True)
        self.treeWidget.setObjectName("treeWidget")
        self.treeWidget.headerItem().setText(0, "1")
        self.horizontalLayout.addWidget(self.treeWidget)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.btnAlgo_UpBlock = QtWidgets.QPushButton(self.tab_pseudocode)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnAlgo_UpBlock.sizePolicy().hasHeightForWidth())
        self.btnAlgo_UpBlock.setSizePolicy(sizePolicy)
        self.btnAlgo_UpBlock.setMinimumSize(QtCore.QSize(0, 28))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/action/media/up_double.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnAlgo_UpBlock.setIcon(icon2)
        self.btnAlgo_UpBlock.setObjectName("btnAlgo_UpBlock")
        self.gridLayout_2.addWidget(self.btnAlgo_UpBlock, 0, 0, 1, 1)
        self.btnAlgo_DownBlock = QtWidgets.QPushButton(self.tab_pseudocode)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnAlgo_DownBlock.sizePolicy().hasHeightForWidth())
        self.btnAlgo_DownBlock.setSizePolicy(sizePolicy)
        self.btnAlgo_DownBlock.setMinimumSize(QtCore.QSize(0, 28))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/action/media/down_double.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnAlgo_DownBlock.setIcon(icon3)
        self.btnAlgo_DownBlock.setObjectName("btnAlgo_DownBlock")
        self.gridLayout_2.addWidget(self.btnAlgo_DownBlock, 1, 0, 1, 1)
        self.btnAlgo_Up = QtWidgets.QPushButton(self.tab_pseudocode)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnAlgo_Up.sizePolicy().hasHeightForWidth())
        self.btnAlgo_Up.setSizePolicy(sizePolicy)
        self.btnAlgo_Up.setMinimumSize(QtCore.QSize(0, 28))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/action/media/up.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnAlgo_Up.setIcon(icon4)
        self.btnAlgo_Up.setObjectName("btnAlgo_Up")
        self.gridLayout_2.addWidget(self.btnAlgo_Up, 0, 1, 1, 1)
        self.btnAlgo_Dupl = QtWidgets.QPushButton(self.tab_pseudocode)
        self.btnAlgo_Dupl.setMinimumSize(QtCore.QSize(0, 28))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/action/media/duplicate_line.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnAlgo_Dupl.setIcon(icon5)
        self.btnAlgo_Dupl.setObjectName("btnAlgo_Dupl")
        self.gridLayout_2.addWidget(self.btnAlgo_Dupl, 1, 3, 1, 1)
        self.btnAlgo_Down = QtWidgets.QPushButton(self.tab_pseudocode)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnAlgo_Down.sizePolicy().hasHeightForWidth())
        self.btnAlgo_Down.setSizePolicy(sizePolicy)
        self.btnAlgo_Down.setMinimumSize(QtCore.QSize(0, 28))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/action/media/down.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnAlgo_Down.setIcon(icon6)
        self.btnAlgo_Down.setObjectName("btnAlgo_Down")
        self.gridLayout_2.addWidget(self.btnAlgo_Down, 1, 1, 1, 1)
        self.btnAlgo_Delete = QtWidgets.QPushButton(self.tab_pseudocode)
        self.btnAlgo_Delete.setMinimumSize(QtCore.QSize(0, 28))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/action/media/delete.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnAlgo_Delete.setIcon(icon7)
        self.btnAlgo_Delete.setObjectName("btnAlgo_Delete")
        self.gridLayout_2.addWidget(self.btnAlgo_Delete, 1, 2, 1, 1)
        self.btnAlgo_Edit = QtWidgets.QPushButton(self.tab_pseudocode)
        self.btnAlgo_Edit.setMinimumSize(QtCore.QSize(0, 28))
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/action/media/edit_line.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnAlgo_Edit.setIcon(icon8)
        self.btnAlgo_Edit.setObjectName("btnAlgo_Edit")
        self.gridLayout_2.addWidget(self.btnAlgo_Edit, 0, 2, 1, 2)
        self.verticalLayout_5.addLayout(self.gridLayout_2)
        self.line_2 = QtWidgets.QFrame(self.tab_pseudocode)
        self.line_2.setLineWidth(1)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_5.addWidget(self.line_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.btnAlgo_ZoomIn = QtWidgets.QPushButton(self.tab_pseudocode)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnAlgo_ZoomIn.sizePolicy().hasHeightForWidth())
        self.btnAlgo_ZoomIn.setSizePolicy(sizePolicy)
        self.btnAlgo_ZoomIn.setMinimumSize(QtCore.QSize(0, 28))
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/action/media/zoom_in.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnAlgo_ZoomIn.setIcon(icon9)
        self.btnAlgo_ZoomIn.setObjectName("btnAlgo_ZoomIn")
        self.horizontalLayout_4.addWidget(self.btnAlgo_ZoomIn)
        self.btnAlgo_ZoomOut = QtWidgets.QPushButton(self.tab_pseudocode)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnAlgo_ZoomOut.sizePolicy().hasHeightForWidth())
        self.btnAlgo_ZoomOut.setSizePolicy(sizePolicy)
        self.btnAlgo_ZoomOut.setMinimumSize(QtCore.QSize(0, 28))
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/action/media/zoom_out.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnAlgo_ZoomOut.setIcon(icon10)
        self.btnAlgo_ZoomOut.setObjectName("btnAlgo_ZoomOut")
        self.horizontalLayout_4.addWidget(self.btnAlgo_ZoomOut)
        self.btnAlgo_ResetZoom = QtWidgets.QPushButton(self.tab_pseudocode)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnAlgo_ResetZoom.sizePolicy().hasHeightForWidth())
        self.btnAlgo_ResetZoom.setSizePolicy(sizePolicy)
        self.btnAlgo_ResetZoom.setMinimumSize(QtCore.QSize(0, 28))
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/action/media/zoom_reset.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnAlgo_ResetZoom.setIcon(icon11)
        self.btnAlgo_ResetZoom.setObjectName("btnAlgo_ResetZoom")
        self.horizontalLayout_4.addWidget(self.btnAlgo_ResetZoom)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        self.line = QtWidgets.QFrame(self.tab_pseudocode)
        self.line.setLineWidth(1)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_5.addWidget(self.line)
        self.tabWidget_2 = QtWidgets.QTabWidget(self.tab_pseudocode)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget_2.sizePolicy().hasHeightForWidth())
        self.tabWidget_2.setSizePolicy(sizePolicy)
        self.tabWidget_2.setMinimumSize(QtCore.QSize(270, 0))
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_basic = QtWidgets.QWidget()
        self.tab_basic.setObjectName("tab_basic")
        self.gridLayout = QtWidgets.QGridLayout(self.tab_basic)
        self.gridLayout.setObjectName("gridLayout")
        self.btnAlgo_Variable = QtWidgets.QPushButton(self.tab_basic)
        self.btnAlgo_Variable.setObjectName("btnAlgo_Variable")
        self.gridLayout.addWidget(self.btnAlgo_Variable, 0, 0, 1, 1)
        self.btnAlgo_Stop = QtWidgets.QPushButton(self.tab_basic)
        self.btnAlgo_Stop.setObjectName("btnAlgo_Stop")
        self.gridLayout.addWidget(self.btnAlgo_Stop, 5, 0, 1, 1)
        self.btnAlgo_Display = QtWidgets.QPushButton(self.tab_basic)
        self.btnAlgo_Display.setObjectName("btnAlgo_Display")
        self.gridLayout.addWidget(self.btnAlgo_Display, 1, 0, 1, 1)
        self.btnAlgo_Comment = QtWidgets.QPushButton(self.tab_basic)
        self.btnAlgo_Comment.setObjectName("btnAlgo_Comment")
        self.gridLayout.addWidget(self.btnAlgo_Comment, 0, 1, 1, 1)
        self.btnAlgo_Input = QtWidgets.QPushButton(self.tab_basic)
        self.btnAlgo_Input.setObjectName("btnAlgo_Input")
        self.gridLayout.addWidget(self.btnAlgo_Input, 1, 1, 1, 1)
        self.tabWidget_2.addTab(self.tab_basic, "")
        self.tab_blocks = QtWidgets.QWidget()
        self.tab_blocks.setObjectName("tab_blocks")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab_blocks)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.btnAlgo_While = QtWidgets.QPushButton(self.tab_blocks)
        self.btnAlgo_While.setObjectName("btnAlgo_While")
        self.gridLayout_4.addWidget(self.btnAlgo_While, 1, 1, 1, 1)
        self.btnAlgo_Else = QtWidgets.QPushButton(self.tab_blocks)
        self.btnAlgo_Else.setObjectName("btnAlgo_Else")
        self.gridLayout_4.addWidget(self.btnAlgo_Else, 0, 1, 1, 1)
        self.btnAlgo_For = QtWidgets.QPushButton(self.tab_blocks)
        self.btnAlgo_For.setObjectName("btnAlgo_For")
        self.gridLayout_4.addWidget(self.btnAlgo_For, 1, 0, 1, 1)
        self.btnAlgo_If = QtWidgets.QPushButton(self.tab_blocks)
        self.btnAlgo_If.setObjectName("btnAlgo_If")
        self.gridLayout_4.addWidget(self.btnAlgo_If, 0, 0, 1, 1)
        self.btnAlgo_Continue = QtWidgets.QPushButton(self.tab_blocks)
        self.btnAlgo_Continue.setObjectName("btnAlgo_Continue")
        self.gridLayout_4.addWidget(self.btnAlgo_Continue, 2, 0, 1, 1)
        self.btnAlgo_Break = QtWidgets.QPushButton(self.tab_blocks)
        self.btnAlgo_Break.setObjectName("btnAlgo_Break")
        self.gridLayout_4.addWidget(self.btnAlgo_Break, 2, 1, 1, 1)
        self.tabWidget_2.addTab(self.tab_blocks, "")
        self.tab_funcs = QtWidgets.QWidget()
        self.tab_funcs.setObjectName("tab_funcs")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tab_funcs)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.btnAlgo_Call = QtWidgets.QPushButton(self.tab_funcs)
        self.btnAlgo_Call.setObjectName("btnAlgo_Call")
        self.gridLayout_5.addWidget(self.btnAlgo_Call, 1, 0, 1, 1)
        self.btnAlgo_Func = QtWidgets.QPushButton(self.tab_funcs)
        self.btnAlgo_Func.setObjectName("btnAlgo_Func")
        self.gridLayout_5.addWidget(self.btnAlgo_Func, 0, 0, 1, 1)
        self.btnAlgo_Return = QtWidgets.QPushButton(self.tab_funcs)
        self.btnAlgo_Return.setObjectName("btnAlgo_Return")
        self.gridLayout_5.addWidget(self.btnAlgo_Return, 2, 0, 1, 1)
        self.tabWidget_2.addTab(self.tab_funcs, "")
        self.tab_plot = QtWidgets.QWidget()
        self.tab_plot.setObjectName("tab_plot")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.tab_plot)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.btnAlgo_GWindow = QtWidgets.QPushButton(self.tab_plot)
        self.btnAlgo_GWindow.setObjectName("btnAlgo_GWindow")
        self.gridLayout_6.addWidget(self.btnAlgo_GWindow, 0, 1, 1, 1)
        self.btnAlgo_GClear = QtWidgets.QPushButton(self.tab_plot)
        self.btnAlgo_GClear.setObjectName("btnAlgo_GClear")
        self.gridLayout_6.addWidget(self.btnAlgo_GClear, 0, 0, 1, 1)
        self.btnAlgo_GPoint = QtWidgets.QPushButton(self.tab_plot)
        self.btnAlgo_GPoint.setObjectName("btnAlgo_GPoint")
        self.gridLayout_6.addWidget(self.btnAlgo_GPoint, 1, 0, 1, 1)
        self.btnAlgo_GLine = QtWidgets.QPushButton(self.tab_plot)
        self.btnAlgo_GLine.setObjectName("btnAlgo_GLine")
        self.gridLayout_6.addWidget(self.btnAlgo_GLine, 1, 1, 1, 1)
        self.tabWidget_2.addTab(self.tab_plot, "")
        self.verticalLayout_5.addWidget(self.tabWidget_2)
        self.horizontalLayout.addLayout(self.verticalLayout_5)
        self.horizontalLayout.setStretch(0, 1)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/action/media/code.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab_pseudocode, icon12, "")
        self.tab_code = QtWidgets.QWidget()
        self.tab_code.setObjectName("tab_code")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.tab_code)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/action/media/python.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab_code, icon13, "")
        self.verticalLayout_2.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 900, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuRecent = QtWidgets.QMenu(self.menuFile)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(":/action/media/recent.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menuRecent.setIcon(icon14)
        self.menuRecent.setObjectName("menuRecent")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuSettings = QtWidgets.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        self.menuChangeTheme = QtWidgets.QMenu(self.menuView)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(":/action/media/theme.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menuChangeTheme.setIcon(icon15)
        self.menuChangeTheme.setObjectName("menuChangeTheme")
        self.menuChangeStyle = QtWidgets.QMenu(self.menuView)
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(":/action/media/style.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menuChangeStyle.setIcon(icon16)
        self.menuChangeStyle.setObjectName("menuChangeStyle")
        self.menuProgram = QtWidgets.QMenu(self.menubar)
        self.menuProgram.setObjectName("menuProgram")
        self.menuTools = QtWidgets.QMenu(self.menubar)
        self.menuTools.setObjectName("menuTools")
        self.menuLanguage = QtWidgets.QMenu(self.menubar)
        self.menuLanguage.setObjectName("menuLanguage")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.dock_output = QtWidgets.QDockWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dock_output.sizePolicy().hasHeightForWidth())
        self.dock_output.setSizePolicy(sizePolicy)
        self.dock_output.setFeatures(QtWidgets.QDockWidget.DockWidgetFloatable|QtWidgets.QDockWidget.DockWidgetMovable)
        self.dock_output.setObjectName("dock_output")
        self.dockWidgetContents_4 = QtWidgets.QWidget()
        self.dockWidgetContents_4.setObjectName("dockWidgetContents_4")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.dockWidgetContents_4)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.txtOutput = QtWidgets.QTextEdit(self.dockWidgetContents_4)
        self.txtOutput.setMinimumSize(QtCore.QSize(310, 0))
        self.txtOutput.setAcceptDrops(False)
        self.txtOutput.setUndoRedoEnabled(True)
        self.txtOutput.setReadOnly(True)
        self.txtOutput.setHtml("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>")
        self.txtOutput.setAcceptRichText(True)
        self.txtOutput.setObjectName("txtOutput")
        self.horizontalLayout_3.addWidget(self.txtOutput)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.btnClearOutput = QtWidgets.QPushButton(self.dockWidgetContents_4)
        self.btnClearOutput.setText("")
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap(":/action/media/log_clear.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnClearOutput.setIcon(icon17)
        self.btnClearOutput.setObjectName("btnClearOutput")
        self.verticalLayout_9.addWidget(self.btnClearOutput)
        self.btnSaveOutput = QtWidgets.QPushButton(self.dockWidgetContents_4)
        self.btnSaveOutput.setText("")
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap(":/action/media/log_save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnSaveOutput.setIcon(icon18)
        self.btnSaveOutput.setObjectName("btnSaveOutput")
        self.verticalLayout_9.addWidget(self.btnSaveOutput)
        self.btnPrintOutput = QtWidgets.QPushButton(self.dockWidgetContents_4)
        self.btnPrintOutput.setText("")
        icon19 = QtGui.QIcon()
        icon19.addPixmap(QtGui.QPixmap(":/action/media/print.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnPrintOutput.setIcon(icon19)
        self.btnPrintOutput.setObjectName("btnPrintOutput")
        self.verticalLayout_9.addWidget(self.btnPrintOutput)
        self.horizontalLayout_3.addLayout(self.verticalLayout_9)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.txtInput = QtWidgets.QLineEdit(self.dockWidgetContents_4)
        self.txtInput.setEnabled(False)
        self.txtInput.setReadOnly(False)
        self.txtInput.setObjectName("txtInput")
        self.horizontalLayout_2.addWidget(self.txtInput)
        self.btnSendInput = QtWidgets.QPushButton(self.dockWidgetContents_4)
        self.btnSendInput.setEnabled(False)
        self.btnSendInput.setText("")
        icon20 = QtGui.QIcon()
        icon20.addPixmap(QtGui.QPixmap(":/action/media/accept.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnSendInput.setIcon(icon20)
        self.btnSendInput.setObjectName("btnSendInput")
        self.horizontalLayout_2.addWidget(self.btnSendInput)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.dock_output.setWidget(self.dockWidgetContents_4)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.dock_output)
        self.dock_plot = QtWidgets.QDockWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dock_plot.sizePolicy().hasHeightForWidth())
        self.dock_plot.setSizePolicy(sizePolicy)
        self.dock_plot.setMinimumSize(QtCore.QSize(300, 260))
        self.dock_plot.setFeatures(QtWidgets.QDockWidget.DockWidgetFloatable|QtWidgets.QDockWidget.DockWidgetMovable)
        self.dock_plot.setObjectName("dock_plot")
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.dock_plot.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.dock_plot)
        self.actionNew = QtWidgets.QAction(MainWindow)
        icon21 = QtGui.QIcon()
        icon21.addPixmap(QtGui.QPixmap(":/action/media/new.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNew.setIcon(icon21)
        self.actionNew.setObjectName("actionNew")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        icon22 = QtGui.QIcon()
        icon22.addPixmap(QtGui.QPixmap(":/action/media/open.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpen.setIcon(icon22)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(MainWindow)
        icon23 = QtGui.QIcon()
        icon23.addPixmap(QtGui.QPixmap(":/action/media/save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSave.setIcon(icon23)
        self.actionSave.setObjectName("actionSave")
        self.actionSaveAs = QtWidgets.QAction(MainWindow)
        icon24 = QtGui.QIcon()
        icon24.addPixmap(QtGui.QPixmap(":/action/media/save_as.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSaveAs.setIcon(icon24)
        self.actionSaveAs.setObjectName("actionSaveAs")
        self.actionClose = QtWidgets.QAction(MainWindow)
        self.actionClose.setObjectName("actionClose")
        self.actionExit = QtWidgets.QAction(MainWindow)
        icon25 = QtGui.QIcon()
        icon25.addPixmap(QtGui.QPixmap(":/action/media/exit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExit.setIcon(icon25)
        self.actionExit.setObjectName("actionExit")
        self.actionSaveAll = QtWidgets.QAction(MainWindow)
        self.actionSaveAll.setObjectName("actionSaveAll")
        self.actionUndo = QtWidgets.QAction(MainWindow)
        icon26 = QtGui.QIcon()
        icon26.addPixmap(QtGui.QPixmap(":/action/media/undo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionUndo.setIcon(icon26)
        self.actionUndo.setObjectName("actionUndo")
        self.actionRedo = QtWidgets.QAction(MainWindow)
        icon27 = QtGui.QIcon()
        icon27.addPixmap(QtGui.QPixmap(":/action/media/redo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRedo.setIcon(icon27)
        self.actionRedo.setObjectName("actionRedo")
        self.actionCut = QtWidgets.QAction(MainWindow)
        icon28 = QtGui.QIcon()
        icon28.addPixmap(QtGui.QPixmap(":/action/media/cut.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCut.setIcon(icon28)
        self.actionCut.setObjectName("actionCut")
        self.actionCopy = QtWidgets.QAction(MainWindow)
        icon29 = QtGui.QIcon()
        icon29.addPixmap(QtGui.QPixmap(":/action/media/copy.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCopy.setIcon(icon29)
        self.actionCopy.setObjectName("actionCopy")
        self.actionPaste = QtWidgets.QAction(MainWindow)
        icon30 = QtGui.QIcon()
        icon30.addPixmap(QtGui.QPixmap(":/action/media/paste.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPaste.setIcon(icon30)
        self.actionPaste.setObjectName("actionPaste")
        self.actionSettings = QtWidgets.QAction(MainWindow)
        icon31 = QtGui.QIcon()
        icon31.addPixmap(QtGui.QPixmap(":/action/media/settings.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSettings.setIcon(icon31)
        self.actionSettings.setObjectName("actionSettings")
        self.actionQuickStart = QtWidgets.QAction(MainWindow)
        icon32 = QtGui.QIcon()
        icon32.addPixmap(QtGui.QPixmap(":/action/media/quick_start.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionQuickStart.setIcon(icon32)
        self.actionQuickStart.setObjectName("actionQuickStart")
        self.actionHelpContents = QtWidgets.QAction(MainWindow)
        icon33 = QtGui.QIcon()
        icon33.addPixmap(QtGui.QPixmap(":/action/media/help.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionHelpContents.setIcon(icon33)
        self.actionHelpContents.setObjectName("actionHelpContents")
        self.actionAboutTuring = QtWidgets.QAction(MainWindow)
        icon34 = QtGui.QIcon()
        icon34.addPixmap(QtGui.QPixmap(":/icon/media/icon_16.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAboutTuring.setIcon(icon34)
        self.actionAboutTuring.setObjectName("actionAboutTuring")
        self.actionShowToolbar = QtWidgets.QAction(MainWindow)
        self.actionShowToolbar.setCheckable(True)
        self.actionShowToolbar.setChecked(True)
        icon35 = QtGui.QIcon()
        icon35.addPixmap(QtGui.QPixmap(":/action/media/toolbar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionShowToolbar.setIcon(icon35)
        self.actionShowToolbar.setObjectName("actionShowToolbar")
        self.actionExamples = QtWidgets.QAction(MainWindow)
        icon36 = QtGui.QIcon()
        icon36.addPixmap(QtGui.QPixmap(":/action/media/examples.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExamples.setIcon(icon36)
        self.actionExamples.setObjectName("actionExamples")
        self.actionPrint = QtWidgets.QAction(MainWindow)
        self.actionPrint.setIcon(icon19)
        self.actionPrint.setObjectName("actionPrint")
        self.actionFind = QtWidgets.QAction(MainWindow)
        icon37 = QtGui.QIcon()
        icon37.addPixmap(QtGui.QPixmap(":/action/media/find.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFind.setIcon(icon37)
        self.actionFind.setObjectName("actionFind")
        self.actionReplace = QtWidgets.QAction(MainWindow)
        icon38 = QtGui.QIcon()
        icon38.addPixmap(QtGui.QPixmap(":/action/media/replace.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionReplace.setIcon(icon38)
        self.actionReplace.setObjectName("actionReplace")
        self.actionCalculator = QtWidgets.QAction(MainWindow)
        icon39 = QtGui.QIcon()
        icon39.addPixmap(QtGui.QPixmap(":/action/media/calculator.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCalculator.setIcon(icon39)
        self.actionCalculator.setObjectName("actionCalculator")
        self.actionClearRecent = QtWidgets.QAction(MainWindow)
        icon40 = QtGui.QIcon()
        icon40.addPixmap(QtGui.QPixmap(":/action/media/recent_clear.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionClearRecent.setIcon(icon40)
        self.actionClearRecent.setObjectName("actionClearRecent")
        self.actionSelectAll = QtWidgets.QAction(MainWindow)
        icon41 = QtGui.QIcon()
        icon41.addPixmap(QtGui.QPixmap(":/action/media/select_all.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSelectAll.setIcon(icon41)
        self.actionSelectAll.setObjectName("actionSelectAll")
        self.actionRun = QtWidgets.QAction(MainWindow)
        icon42 = QtGui.QIcon()
        icon42.addPixmap(QtGui.QPixmap(":/action/media/run.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRun.setIcon(icon42)
        self.actionRun.setObjectName("actionRun")
        self.actionStep = QtWidgets.QAction(MainWindow)
        icon43 = QtGui.QIcon()
        icon43.addPixmap(QtGui.QPixmap(":/action/media/step.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionStep.setIcon(icon43)
        self.actionStep.setObjectName("actionStep")
        self.actionShowToolbarText = QtWidgets.QAction(MainWindow)
        self.actionShowToolbarText.setCheckable(True)
        self.actionShowToolbarText.setChecked(True)
        icon44 = QtGui.QIcon()
        icon44.addPixmap(QtGui.QPixmap(":/action/media/toolbar_text.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionShowToolbarText.setIcon(icon44)
        self.actionShowToolbarText.setObjectName("actionShowToolbarText")
        self.actionConvertToPython = QtWidgets.QAction(MainWindow)
        self.actionConvertToPython.setIcon(icon13)
        self.actionConvertToPython.setObjectName("actionConvertToPython")
        self.actionConvertToPseudocode = QtWidgets.QAction(MainWindow)
        self.actionConvertToPseudocode.setEnabled(False)
        self.actionConvertToPseudocode.setIcon(icon12)
        self.actionConvertToPseudocode.setObjectName("actionConvertToPseudocode")
        self.actionEnglish = QtWidgets.QAction(MainWindow)
        self.actionEnglish.setCheckable(True)
        icon45 = QtGui.QIcon()
        icon45.addPixmap(QtGui.QPixmap(":/lang/media/lang/english.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionEnglish.setIcon(icon45)
        self.actionEnglish.setText("English")
        self.actionEnglish.setStatusTip("en")
        self.actionEnglish.setObjectName("actionEnglish")
        self.actionFrench = QtWidgets.QAction(MainWindow)
        self.actionFrench.setCheckable(True)
        icon46 = QtGui.QIcon()
        icon46.addPixmap(QtGui.QPixmap(":/lang/media/lang/french.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFrench.setIcon(icon46)
        self.actionFrench.setText("Français")
        self.actionFrench.setStatusTip("fr")
        self.actionFrench.setObjectName("actionFrench")
        self.actionDuplicateLine = QtWidgets.QAction(MainWindow)
        self.actionDuplicateLine.setIcon(icon5)
        self.actionDuplicateLine.setObjectName("actionDuplicateLine")
        self.actionIndent = QtWidgets.QAction(MainWindow)
        icon47 = QtGui.QIcon()
        icon47.addPixmap(QtGui.QPixmap(":/action/media/indent.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionIndent.setIcon(icon47)
        self.actionIndent.setObjectName("actionIndent")
        self.actionUnindent = QtWidgets.QAction(MainWindow)
        icon48 = QtGui.QIcon()
        icon48.addPixmap(QtGui.QPixmap(":/action/media/unindent.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionUnindent.setIcon(icon48)
        self.actionUnindent.setObjectName("actionUnindent")
        self.actionGoToLine = QtWidgets.QAction(MainWindow)
        icon49 = QtGui.QIcon()
        icon49.addPixmap(QtGui.QPixmap(":/action/media/go_to_line.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionGoToLine.setIcon(icon49)
        self.actionGoToLine.setObjectName("actionGoToLine")
        self.actionFindPrevious = QtWidgets.QAction(MainWindow)
        icon50 = QtGui.QIcon()
        icon50.addPixmap(QtGui.QPixmap(":/action/media/find_previous.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFindPrevious.setIcon(icon50)
        self.actionFindPrevious.setObjectName("actionFindPrevious")
        self.actionFindNext = QtWidgets.QAction(MainWindow)
        icon51 = QtGui.QIcon()
        icon51.addPixmap(QtGui.QPixmap(":/action/media/find_next.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFindNext.setIcon(icon51)
        self.actionFindNext.setObjectName("actionFindNext")
        self.actionStop = QtWidgets.QAction(MainWindow)
        self.actionStop.setEnabled(False)
        icon52 = QtGui.QIcon()
        icon52.addPixmap(QtGui.QPixmap(":/action/media/stop.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionStop.setIcon(icon52)
        self.actionStop.setObjectName("actionStop")
        self.actionDebug = QtWidgets.QAction(MainWindow)
        icon53 = QtGui.QIcon()
        icon53.addPixmap(QtGui.QPixmap(":/action/media/debug.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDebug.setIcon(icon53)
        self.actionDebug.setVisible(False)
        self.actionDebug.setObjectName("actionDebug")
        self.actionSendFeedback = QtWidgets.QAction(MainWindow)
        icon54 = QtGui.QIcon()
        icon54.addPixmap(QtGui.QPixmap(":/action/media/feedback.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSendFeedback.setIcon(icon54)
        self.actionSendFeedback.setObjectName("actionSendFeedback")
        self.actionZoomIn = QtWidgets.QAction(MainWindow)
        self.actionZoomIn.setIcon(icon9)
        self.actionZoomIn.setObjectName("actionZoomIn")
        self.actionZoomOut = QtWidgets.QAction(MainWindow)
        self.actionZoomOut.setIcon(icon10)
        self.actionZoomOut.setObjectName("actionZoomOut")
        self.actionResetZoom = QtWidgets.QAction(MainWindow)
        self.actionResetZoom.setIcon(icon11)
        self.actionResetZoom.setObjectName("actionResetZoom")
        self.menuRecent.addAction(self.actionClearRecent)
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSaveAs)
        self.menuFile.addAction(self.actionSaveAll)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionPrint)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.menuRecent.menuAction())
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuEdit.addAction(self.actionUndo)
        self.menuEdit.addAction(self.actionRedo)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionCut)
        self.menuEdit.addAction(self.actionCopy)
        self.menuEdit.addAction(self.actionPaste)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionSelectAll)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionFind)
        self.menuEdit.addAction(self.actionFindPrevious)
        self.menuEdit.addAction(self.actionFindNext)
        self.menuEdit.addAction(self.actionReplace)
        self.menuEdit.addAction(self.actionGoToLine)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionDuplicateLine)
        self.menuEdit.addAction(self.actionIndent)
        self.menuEdit.addAction(self.actionUnindent)
        self.menuSettings.addAction(self.actionSettings)
        self.menuHelp.addAction(self.actionQuickStart)
        self.menuHelp.addAction(self.actionHelpContents)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionExamples)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionSendFeedback)
        self.menuHelp.addAction(self.actionAboutTuring)
        self.menuView.addAction(self.actionShowToolbar)
        self.menuView.addAction(self.actionShowToolbarText)
        self.menuView.addSeparator()
        self.menuView.addAction(self.menuChangeTheme.menuAction())
        self.menuView.addAction(self.menuChangeStyle.menuAction())
        self.menuView.addSeparator()
        self.menuView.addAction(self.actionZoomIn)
        self.menuView.addAction(self.actionZoomOut)
        self.menuView.addAction(self.actionResetZoom)
        self.menuProgram.addAction(self.actionRun)
        self.menuProgram.addAction(self.actionDebug)
        self.menuProgram.addAction(self.actionStep)
        self.menuProgram.addAction(self.actionStop)
        self.menuProgram.addSeparator()
        self.menuProgram.addAction(self.actionConvertToPython)
        self.menuProgram.addAction(self.actionConvertToPseudocode)
        self.menuTools.addAction(self.actionCalculator)
        self.menuLanguage.addAction(self.actionEnglish)
        self.menuLanguage.addAction(self.actionFrench)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuProgram.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.menubar.addAction(self.menuLanguage.menuAction())
        self.toolBar.addAction(self.actionNew)
        self.toolBar.addAction(self.actionOpen)
        self.toolBar.addAction(self.actionSave)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionUndo)
        self.toolBar.addAction(self.actionRedo)
        self.toolBar.addAction(self.actionFind)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionRun)
        self.toolBar.addAction(self.actionDebug)
        self.toolBar.addAction(self.actionStep)
        self.toolBar.addAction(self.actionStop)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionHelpContents)
        self.toolBar.addAction(self.actionSendFeedback)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        self.tabWidget_2.setCurrentIndex(0)
        self.txtInput.returnPressed.connect(self.btnSendInput.click)
        self.btnAlgo_ZoomIn.clicked.connect(self.actionZoomIn.trigger)
        self.btnAlgo_ZoomOut.clicked.connect(self.actionZoomOut.trigger)
        self.btnAlgo_ResetZoom.clicked.connect(self.actionResetZoom.trigger)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.btnClearOutput, self.btnSaveOutput)
        MainWindow.setTabOrder(self.btnSaveOutput, self.btnPrintOutput)
        MainWindow.setTabOrder(self.btnPrintOutput, self.txtInput)
        MainWindow.setTabOrder(self.txtInput, self.btnSendInput)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Turing"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_home), _translate("MainWindow", "Home"))
        self.btnAlgo_Dupl.setText(_translate("MainWindow", "Duplicate Line", "shorter"))
        self.btnAlgo_Delete.setText(_translate("MainWindow", "Delete Line"))
        self.btnAlgo_Edit.setText(_translate("MainWindow", "Edit Line"))
        self.btnAlgo_ZoomIn.setText(_translate("MainWindow", "Zoom in"))
        self.btnAlgo_ZoomOut.setText(_translate("MainWindow", "Zoom out"))
        self.btnAlgo_ResetZoom.setText(_translate("MainWindow", "Reset zoom"))
        self.btnAlgo_Variable.setText(_translate("MainWindow", "DEFINE variable"))
        self.btnAlgo_Stop.setText(_translate("MainWindow", "Breakpoint"))
        self.btnAlgo_Display.setText(_translate("MainWindow", "DISPLAY value"))
        self.btnAlgo_Comment.setText(_translate("MainWindow", "Comment"))
        self.btnAlgo_Input.setText(_translate("MainWindow", "Read user INPUT"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_basic), _translate("MainWindow", "Basic"))
        self.btnAlgo_While.setText(_translate("MainWindow", "WHILE loop"))
        self.btnAlgo_Else.setText(_translate("MainWindow", "ELSE block"))
        self.btnAlgo_For.setText(_translate("MainWindow", "FOR loop"))
        self.btnAlgo_If.setText(_translate("MainWindow", "IF block"))
        self.btnAlgo_Continue.setText(_translate("MainWindow", "CONTINUE"))
        self.btnAlgo_Break.setText(_translate("MainWindow", "BREAK"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_blocks), _translate("MainWindow", "Blocks"))
        self.btnAlgo_Call.setText(_translate("MainWindow", "CALL function"))
        self.btnAlgo_Func.setText(_translate("MainWindow", "Define FUNCTION"))
        self.btnAlgo_Return.setText(_translate("MainWindow", "RETURN"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_funcs), _translate("MainWindow", "Functions"))
        self.btnAlgo_GWindow.setText(_translate("MainWindow", "Set window"))
        self.btnAlgo_GClear.setText(_translate("MainWindow", "Clear plot"))
        self.btnAlgo_GPoint.setText(_translate("MainWindow", "Draw point"))
        self.btnAlgo_GLine.setText(_translate("MainWindow", "Draw line"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_plot), _translate("MainWindow", "Plot"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_pseudocode), _translate("MainWindow", "Pseudocode"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_code), _translate("MainWindow", "Code"))
        self.menuFile.setTitle(_translate("MainWindow", "&File"))
        self.menuRecent.setTitle(_translate("MainWindow", "Recent files"))
        self.menuEdit.setTitle(_translate("MainWindow", "&Edit"))
        self.menuSettings.setTitle(_translate("MainWindow", "&Settings"))
        self.menuHelp.setTitle(_translate("MainWindow", "&Help"))
        self.menuView.setTitle(_translate("MainWindow", "&View"))
        self.menuChangeTheme.setTitle(_translate("MainWindow", "Change theme"))
        self.menuChangeStyle.setTitle(_translate("MainWindow", "Change style"))
        self.menuProgram.setTitle(_translate("MainWindow", "&Program"))
        self.menuTools.setTitle(_translate("MainWindow", "&Tools"))
        self.menuLanguage.setTitle(_translate("MainWindow", "&Language"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "Toolbar"))
        self.dock_output.setWindowTitle(_translate("MainWindow", "Output"))
        self.btnClearOutput.setToolTip(_translate("MainWindow", "Clear Output"))
        self.btnSaveOutput.setToolTip(_translate("MainWindow", "Save Output"))
        self.btnPrintOutput.setToolTip(_translate("MainWindow", "Print Output"))
        self.dock_plot.setWindowTitle(_translate("MainWindow", "Plot"))
        self.actionNew.setText(_translate("MainWindow", "New"))
        self.actionNew.setToolTip(_translate("MainWindow", "New"))
        self.actionNew.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionOpen.setToolTip(_translate("MainWindow", "Open"))
        self.actionOpen.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionSave.setToolTip(_translate("MainWindow", "Save"))
        self.actionSave.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionSaveAs.setText(_translate("MainWindow", "Save As"))
        self.actionSaveAs.setToolTip(_translate("MainWindow", "Save As"))
        self.actionClose.setText(_translate("MainWindow", "Close"))
        self.actionClose.setToolTip(_translate("MainWindow", "Close"))
        self.actionClose.setShortcut(_translate("MainWindow", "Ctrl+W"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionExit.setToolTip(_translate("MainWindow", "Exit"))
        self.actionExit.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.actionSaveAll.setText(_translate("MainWindow", "Save All"))
        self.actionSaveAll.setToolTip(_translate("MainWindow", "Save All"))
        self.actionSaveAll.setShortcut(_translate("MainWindow", "Ctrl+Shift+S"))
        self.actionUndo.setText(_translate("MainWindow", "Undo"))
        self.actionUndo.setToolTip(_translate("MainWindow", "Undo"))
        self.actionUndo.setShortcut(_translate("MainWindow", "Ctrl+Z"))
        self.actionRedo.setText(_translate("MainWindow", "Redo"))
        self.actionRedo.setToolTip(_translate("MainWindow", "Redo"))
        self.actionRedo.setShortcut(_translate("MainWindow", "Ctrl+Y"))
        self.actionCut.setText(_translate("MainWindow", "Cut"))
        self.actionCut.setToolTip(_translate("MainWindow", "Cut"))
        self.actionCut.setShortcut(_translate("MainWindow", "Ctrl+X"))
        self.actionCopy.setText(_translate("MainWindow", "Copy"))
        self.actionCopy.setToolTip(_translate("MainWindow", "Copy"))
        self.actionCopy.setShortcut(_translate("MainWindow", "Ctrl+C"))
        self.actionPaste.setText(_translate("MainWindow", "Paste"))
        self.actionPaste.setToolTip(_translate("MainWindow", "Paste"))
        self.actionPaste.setShortcut(_translate("MainWindow", "Ctrl+V"))
        self.actionSettings.setText(_translate("MainWindow", "Settings"))
        self.actionSettings.setToolTip(_translate("MainWindow", "Settings"))
        self.actionQuickStart.setText(_translate("MainWindow", "Quick Start"))
        self.actionQuickStart.setToolTip(_translate("MainWindow", "Quick Start"))
        self.actionHelpContents.setText(_translate("MainWindow", "Help Contents"))
        self.actionHelpContents.setToolTip(_translate("MainWindow", "Help Contents"))
        self.actionHelpContents.setShortcut(_translate("MainWindow", "F1"))
        self.actionAboutTuring.setText(_translate("MainWindow", "About Turing"))
        self.actionAboutTuring.setToolTip(_translate("MainWindow", "About Turing"))
        self.actionShowToolbar.setText(_translate("MainWindow", "Show toolbar"))
        self.actionShowToolbar.setToolTip(_translate("MainWindow", "Show toolbar"))
        self.actionExamples.setText(_translate("MainWindow", "Examples"))
        self.actionPrint.setText(_translate("MainWindow", "Print"))
        self.actionPrint.setToolTip(_translate("MainWindow", "Print"))
        self.actionPrint.setShortcut(_translate("MainWindow", "Ctrl+P"))
        self.actionFind.setText(_translate("MainWindow", "Find"))
        self.actionFind.setToolTip(_translate("MainWindow", "Find"))
        self.actionReplace.setText(_translate("MainWindow", "Replace"))
        self.actionReplace.setToolTip(_translate("MainWindow", "Replace"))
        self.actionCalculator.setText(_translate("MainWindow", "Calculator"))
        self.actionCalculator.setToolTip(_translate("MainWindow", "Calculator"))
        self.actionClearRecent.setText(_translate("MainWindow", "Clear"))
        self.actionClearRecent.setToolTip(_translate("MainWindow", "Clear"))
        self.actionSelectAll.setText(_translate("MainWindow", "Select All"))
        self.actionSelectAll.setToolTip(_translate("MainWindow", "Select All"))
        self.actionSelectAll.setShortcut(_translate("MainWindow", "Ctrl+A"))
        self.actionRun.setText(_translate("MainWindow", "Run"))
        self.actionRun.setToolTip(_translate("MainWindow", "Run"))
        self.actionRun.setShortcut(_translate("MainWindow", "F5"))
        self.actionStep.setText(_translate("MainWindow", "Step-by-step"))
        self.actionStep.setToolTip(_translate("MainWindow", "Step-by-step"))
        self.actionStep.setShortcut(_translate("MainWindow", "F10"))
        self.actionShowToolbarText.setText(_translate("MainWindow", "Show toolbar text"))
        self.actionShowToolbarText.setToolTip(_translate("MainWindow", "Show toolbar text"))
        self.actionConvertToPython.setText(_translate("MainWindow", "Convert to Python"))
        self.actionConvertToPython.setToolTip(_translate("MainWindow", "Convert to Python"))
        self.actionConvertToPseudocode.setText(_translate("MainWindow", "Convert to pseudocode"))
        self.actionConvertToPseudocode.setToolTip(_translate("MainWindow", "Convert to pseudocode"))
        self.actionDuplicateLine.setText(_translate("MainWindow", "Duplicate Line"))
        self.actionDuplicateLine.setShortcut(_translate("MainWindow", "Ctrl+D"))
        self.actionIndent.setText(_translate("MainWindow", "Indent"))
        self.actionIndent.setShortcut(_translate("MainWindow", "Tab"))
        self.actionUnindent.setText(_translate("MainWindow", "Unindent"))
        self.actionUnindent.setShortcut(_translate("MainWindow", "Shift+Tab"))
        self.actionGoToLine.setText(_translate("MainWindow", "Go To Line"))
        self.actionGoToLine.setShortcut(_translate("MainWindow", "Ctrl+G"))
        self.actionFindPrevious.setText(_translate("MainWindow", "Find Previous"))
        self.actionFindPrevious.setShortcut(_translate("MainWindow", "Shift+F3"))
        self.actionFindNext.setText(_translate("MainWindow", "Find Next"))
        self.actionFindNext.setShortcut(_translate("MainWindow", "F3"))
        self.actionStop.setText(_translate("MainWindow", "Stop"))
        self.actionDebug.setText(_translate("MainWindow", "Debug"))
        self.actionSendFeedback.setText(_translate("MainWindow", "Send Feedback"))
        self.actionZoomIn.setText(_translate("MainWindow", "Zoom in"))
        self.actionZoomOut.setText(_translate("MainWindow", "Zoom out"))
        self.actionResetZoom.setText(_translate("MainWindow", "Reset zoom"))

import turing_rc
